apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-nextjs-app.fullname" . | quote }}
  namespace: {{ include "spring-nextjs-app.namespace" . | quote }}
  labels: {{- include "spring-nextjs-app.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: spring-nextjs-app
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "spring-nextjs-app.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.spring.datasource.url | quote }}
