apiVersion: v1
kind: Secret
metadata:
    name: {{ template "spring-nextjs-app.fullname" . }}
    namespace: {{ include "spring-nextjs-app.namespace" . | quote }}
    labels: {{- include "spring-nextjs-app.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "spring-nextjs-app.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
   {{- end }}
type: Opaque
data:
    datasource-username: {{ .Values.spring.datasource.username | b64enc | quote }}
    datasource-password: {{ .Values.spring.datasource.password | b64enc | quote }}
