server:
  port: 8080

spring:
  devtools:
    livereload:
      enabled: true
  messages:
    cache-duration: 1h
  restclient:
    connect-timeout: 5s
    read-timeout: 10s
  liquibase:
    contexts: local
  mvc:
    cors:
      enabled: true
      allowed-origins: "http://localhost:3000,http://localhost:8888,http://localhost:8080,app://."
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
      allowed-headers: "Authorization,Accept-Language,Content-Type,Accept,Cache-Control,X-Requested-With,Origin,Referer,User-Agent"
      allow-credentials: true
      max-age: 3600
  datasource:
    url: jdbc:h2:mem:demo;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: admin
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 1
      pool-name: Hikari
      auto-commit: false
  jpa:
    show-sql: true
  cache:
    default-config:
      ttl: 1h
      initial-capacity: 5000
      maximum-size: 10000
    hibernate:
      default-update-timestamps-region:
        ttl: 1h
        initial-capacity: 5000
        maximum-size: 10000
      default-query-results-region:
        ttl: 1h
        initial-capacity: 5000
        maximum-size: 10000
  graphql:
    graphiql:
      enabled: true
      props:
        variables:
          headerEditorEnabled: true

logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    io.github.susimsek.springnextjssamples: DEBUG
  async:
    queueSize: 10000
    discardingThreshold: 0
    maxFlushTime: 5000
    includeCallerData: false
  loki:
    enabled: false
    url: http://localhost:3100/loki/api/v1/push
  aspect:
    enabled: true
    log-level: FULL
  http:
    enabled: true
    log-level: FULL
  obfuscate:
    enabled: true

management:
  tracing:
    enabled: false
  zipkin:
    tracing:
      endpoint: http://localhost:9411

security:
  content-security-policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com; style-src 'self' 'unsafe-inline' https://unpkg.com; worker-src 'self' blob:; img-src 'self' data:; frame-src 'self' app://. http://localhost:8080 data:; font-src 'self' data:; frame-ancestors 'self' http://localhost:8080;"
  token:
    jwe-enabled: true
    key-id: 3f8a8e5b-89f4-4b7d-91e1-5b5c1d4e7b9c
    access-token-time-to-live: PT1H
