architecture: standalone
global:
  postgresql:
    auth:
      postgresPassword: root
primary:
  service:
    type: LoadBalancer
  initdb:
    scripts:
      initdb.sql: |
        CREATE USER admin WITH PASSWORD 'root';
        CREATE DATABASE demo WITH OWNER = admin ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;

image:
  repository: suayb/bitnami-debezium-postgresql
  tag: 15.4.0
