version: "3.8"

services:
  postgresql:
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - postgresql:/bitnami/postgresql
    extends:
      file: common-config.yml
      service: app-db-config

  app:
    image: suayb/spring-nextjs-app:main
    container_name: app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/demo
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent localhost:7080/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: app-base-config

networks:
  app:
    driver: "bridge"

volumes:
  postgresql:
