name: Build, Test, and Publish Application

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  desktop-build:
    name: Desktop macOS Build
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
    env:
      NODE_VERSION: 21.6.0
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.6.0
          cache: 'npm'
          cache-dependency-path: src/main/desktop/package-lock.json

      # Install Node.js dependencies for the desktop application
      - name: Install Node.js Packages
        working-directory: src/main/desktop
        run: npm install

      # Build the desktop application
      - name: Build Desktop Application
        working-directory: src/main/desktop
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #      # Publish the desktop application to GitHub Releases
  #      - name: Publish Desktop Application
  #        working-directory: src/main/desktop
  #        run: npm run publish
  #        env:
  #          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      NODE_VERSION: 21.6.0
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Snyk
      - name: Set up Snyk
        uses: snyk/actions/setup@master
        with:
          version: 'latest'

      # Set up Node 21
      - name: Set up Node 21
        uses: actions/setup-node@v4
        with:
          node-version: 21.6.0
          cache: 'npm'
          cache-dependency-path: src/main/webapp/package-lock.json

      # Set up Java Development Kit (JDK) with GraalVM
      - name: Set up JDK 22 with GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'liberica'
          version: '22.3.0'
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      # Print Java, Maven, Node, Npm Version
      - name: Print Java, Maven, Node, Npm Version
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          mvn --version
          node -v
          npm --version

      # Configure Maven settings for GitHub Packages
      - name: Configure Maven for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GITHUB_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>' > ~/.m2/settings.xml

      # Install Node.js dependencies for the web application
      - name: Install Node.js Packages for WebApp
        working-directory: src/main/webapp
        run: npm install

      # Download all required dependencies for Maven
      - name: Download Dependencies
        run: mvn -ntp dependency:go-offline

      # Run unit and integration tests for the backend
      - name: Run Tests
        run: mvn -ntp -Dskip.installnodenpm -Dskip.npm verify --batch-mode

      # Perform quality analysis using SonarQube
      - name: Run Quality Analysis
        run: mvn -ntp -Psonar initialize sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      # Deploy the backend application to GitHub Packages
      - name: Deploy to GitHub Packages
        run: mvn deploy -Pprod -Dgpg.skip -Dgithub -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build and publish Docker image for the backend
      - name: Build and Publish Docker Image
        run: |
          mvn -ntp -Pprod jib:build -DskipTests -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }} -Djib.to.image=docker.io/${{ secrets.DOCKER_USERNAME }}/spring-nextjs-app:${{ github.ref_name }}
